In [ ]:
%load_ext autoreload
%autoreload 2

In [2]:
import yaml
from easydict import EasyDict

import torch
from transformers import ElectraTokenizer#, ElectraModel
from optimum.graphcore import IPUSeq2SeqTrainingArguments as Seq2SeqTrainingArguments

from modeling_electra import ElectraModel, ElectraForMaskedLM
from ipu_configuration import IPUConfig, ipu_options
import inspect


tokenizer = ElectraTokenizer.from_pretrained('google/electra-small-generator')
model = ElectraForMaskedLM.from_pretrained('google/electra-small-generator')

input_ids = tokenizer("Hello, my dog is cute", return_tensors="pt")["input_ids"]

outputs = model(input_ids, labels=input_ids)
loss, prediction_scores = outputs[:2]

In [3]:
input_value = tokenizer.encode_plus("Hello, my dog is cute", return_tensors="pt", padding="max_length")

In [4]:
model(**input_value)

MaskedLMOutput(loss=None, logits=tensor([[[ 11.1353,  -7.4241,  -7.4119,  ...,  -7.4380,  -7.4108,  -7.3961],
         [ -9.8389, -10.2289, -10.2246,  ..., -10.2524, -10.2351, -10.0815],
         [  3.9714, -10.9872, -10.9838,  ..., -10.9641, -10.9766, -10.8934],
         ...,
         [ 50.3298,   1.1282,   1.1599,  ...,   1.0819,   1.2214,   1.1251],
         [ 49.8866,   0.8877,   0.9184,  ...,   0.8425,   0.9800,   0.8855],
         [ 11.1366,  -7.4236,  -7.4115,  ...,  -7.4376,  -7.4104,  -7.3956]]],
       grad_fn=<AddBackward0>), hidden_states=None, attentions=None)

In [5]:
# from transformers import BertConfig, ElectraConfig
# bert_config = BertConfig.from_pretrained('bert-base-uncased')
# electra_config = ElectraConfig.from_pretrained('google/electra-small-discriminator')
# print(bert_config)
# print(electra_config)

In [6]:
signature = inspect.signature(model.forward)
signature

<Signature (input_ids:Union[torch.Tensor, NoneType]=None, attention_mask:Union[torch.Tensor, NoneType]=None, token_type_ids:Union[torch.Tensor, NoneType]=None, position_ids:Union[torch.Tensor, NoneType]=None, head_mask:Union[torch.Tensor, NoneType]=None, inputs_embeds:Union[torch.Tensor, NoneType]=None, labels:Union[torch.Tensor, NoneType]=None, output_attentions:Union[bool, NoneType]=None, output_hidden_states:Union[bool, NoneType]=None, return_dict:Union[bool, NoneType]=None) -> Union[Tuple, transformers.modeling_outputs.MaskedLMOutput]>

In [7]:
!ls

__init__.py		  data			ipu_electra.ipynb
__pycache__		  exe_cache		ipu_train.py
bert_test.ipynb		  finetune		modeling_electra.py
checkpoints		  inference.py		pipeline_electra.py
configuration_electra.py  input.txt		server.py
configurations		  ipu_configuration.py	test.py


In [8]:
# model error
#pipelinedElectraForMaskedLM

# IPU Config 

In [9]:
from pipeline_electra import pipelinedElectraForMaskedLM

ImportError: cannot import name 'pipelinedElectraForMaskedLM'

In [17]:
train_ipu_config = {
    "layers_per_ipu": [2,3,4,3],
    "recompute_checkpoint_every_layer":True,
    "embedding_serialization_factor": 1
}

train_ipu_config = EasyDict(train_ipu_config)

In [21]:
ipu_options

In [22]:
opts = ipu_config.to_options()

optimizer_class = torch.optim.AdamW
optimizer = optimizer_class(model.parameters(), lr=0.004)

Setting replicated_tensor_sharding to False when replication_factor=1


In [23]:
model.resize_token_embeddings(len(tokenizer))

Embedding(30522, 128, padding_idx=0)

In [24]:
from pipeline_electra import PipelinedElectraForMaskedLM, PipelinedElectraModel, _PRETRAINED_TO_PIPELINED_REGISTRY

In [25]:
#ipu_model = PipelinedElectraForMaskedLM.from_transformers(model, ipu_config)
ipu_model = WrappedModel(model)

In [11]:
#opts.toDict()

In [29]:
tuple_data = (input_value['input_ids'], input_value['token_type_ids'])#, input_value['attention_mask'])

In [30]:
ipu_model(*tuple_data)#**input_value)

(None,
 tensor([[[ 54.9057,  -5.3235,  -5.2913,  ...,  -5.3311,  -5.2803,  -5.2297],
          [  4.3153,  -7.6142,  -7.5974,  ...,  -7.6405,  -7.5978,  -7.4839],
          [  0.6850, -10.1405, -10.1285,  ..., -10.1082, -10.1080, -10.0778],
          ...,
          [ 51.8493,  -6.1342,  -6.1186,  ...,  -6.1448,  -6.0973,  -6.0254],
          [ 51.9255,  -5.9819,  -5.9638,  ...,  -5.9926,  -5.9437,  -5.8599],
          [ 54.9085,  -5.3233,  -5.2912,  ...,  -5.3309,  -5.2801,  -5.2295]]],
        grad_fn=<AddBackward0>))

In [32]:
from finetune.run_squad_ipu import ipu_options
val_opts = ipu_options(1, 1, 1, train_option=False)

In [33]:
t_model = poptorch.trainingModel(ipu_model.train(), options=opts, optimizer=optimizer)

In [38]:
t_model.compile(input_value['input_ids'])

RuntimeError: Tracer cannot infer type of (tensor([[  101,  7592,  1010,  2026,  3899,  2003, 10140,   102,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0]]), <class 'inspect._empty'>)
:Only tensors and (possibly nested) tuples of tensors, lists, or dictsare supported as inputs or outputs of traced functions, but instead got value of type type.

In [37]:
input_value['input_ids'].shape

torch.Size([1, 512])

In [65]:
model.electra.encoder.layer[2]

ElectraLayer(
  (attention): ElectraAttention(
    (self): ElectraSelfAttention(
      (query): Linear(in_features=256, out_features=256, bias=True)
      (key): Linear(in_features=256, out_features=256, bias=True)
      (value): Linear(in_features=256, out_features=256, bias=True)
      (dropout): Dropout(p=0.1, inplace=False)
    )
    (output): ElectraSelfOutput(
      (dense): Linear(in_features=256, out_features=256, bias=True)
      (LayerNorm): LayerNorm((256,), eps=1e-12, elementwise_affine=True)
      (dropout): Dropout(p=0.1, inplace=False)
    )
  )
  (intermediate): ElectraIntermediate(
    (dense): Linear(in_features=256, out_features=1024, bias=True)
    (intermediate_act_fn): GELUActivation()
  )
  (output): ElectraOutput(
    (dense): Linear(in_features=1024, out_features=256, bias=True)
    (LayerNorm): LayerNorm((256,), eps=1e-12, elementwise_affine=True)
    (dropout): Dropout(p=0.1, inplace=False)
  )
)

In [22]:
from torch.utils.data import Dataset
import os

In [24]:
class CharDataset(Dataset):
    def __init__(self, data, block_size):
        chars = sorted(list(set(data)))
        data_size, vocab_size = len(data), len(chars)
        print('data has %d characters, %d unique.' % (data_size, vocab_size))

        self.stoi = {ch: i for i, ch in enumerate(chars)}
        self.itos = {i: ch for i, ch in enumerate(chars)}
        self.block_size = block_size
        self.vocab_size = vocab_size
        self.data = data

    def __len__(self):
        return len(self.data) - self.block_size

    def __getitem__(self, idx):
        # grab a chunk of (block_size + 1) characters from the data
        chunk = self.data[idx:idx + self.block_size + 1]
        # encode every character to an integer
        dix = [self.stoi[s] for s in chunk]
        x = torch.tensor(dix[:-1], dtype=torch.long)
        y = torch.tensor(dix[1:], dtype=torch.long)
        return x, y


block_size = 128  # spatial extent of the model for its context
if not os.path.isfile('input.txt'):
    os.system('wget https://github.com/karpathy/char-rnn/raw/master/data/tinyshakespeare/input.txt')
text = open('input.txt', 'r').read()  # don't worry we won't run out of file handles
train_dataset = CharDataset(text, block_size)  # one line of poem is roughly 50 characters

data has 1115394 characters, 65 unique.


In [26]:
train_dataset[0]

(tensor([18, 47, 56, 57, 58,  1, 15, 47, 58, 47, 64, 43, 52, 10,  0, 14, 43, 44,
         53, 56, 43,  1, 61, 43,  1, 54, 56, 53, 41, 43, 43, 42,  1, 39, 52, 63,
          1, 44, 59, 56, 58, 46, 43, 56,  6,  1, 46, 43, 39, 56,  1, 51, 43,  1,
         57, 54, 43, 39, 49,  8,  0,  0, 13, 50, 50, 10,  0, 31, 54, 43, 39, 49,
          6,  1, 57, 54, 43, 39, 49,  8,  0,  0, 18, 47, 56, 57, 58,  1, 15, 47,
         58, 47, 64, 43, 52, 10,  0, 37, 53, 59,  1, 39, 56, 43,  1, 39, 50, 50,
          1, 56, 43, 57, 53, 50, 60, 43, 42,  1, 56, 39, 58, 46, 43, 56,  1, 58,
         53,  1]),
 tensor([47, 56, 57, 58,  1, 15, 47, 58, 47, 64, 43, 52, 10,  0, 14, 43, 44, 53,
         56, 43,  1, 61, 43,  1, 54, 56, 53, 41, 43, 43, 42,  1, 39, 52, 63,  1,
         44, 59, 56, 58, 46, 43, 56,  6,  1, 46, 43, 39, 56,  1, 51, 43,  1, 57,
         54, 43, 39, 49,  8,  0,  0, 13, 50, 50, 10,  0, 31, 54, 43, 39, 49,  6,
          1, 57, 54, 43, 39, 49,  8,  0,  0, 18, 47, 56, 57, 58,  1, 15, 47, 58,
         

In [30]:
tuple_data

(tensor([[  101,  7592,  1010,  2026,  3899,  2003, 10140,   102]]),
 tensor([[0, 0, 0, 0, 0, 0, 0, 0]]),
 tensor([[1, 1, 1, 1, 1, 1, 1, 1]]))